version: 1
enabled: true

# Custom instructions for the agent
instructions: |
  - This repository is used to test the GitHub SRE Agent
  - For any workflow failure classified as a real bug or configuration issue, ALWAYS create a GitHub issue
  - Do not limit actions to notes-only for such failures
  - Use labels including "ci-failure"

# Action-specific settings
actions:
  retry:
    enabled: true
    maxAttempts: 3
    
  createIssue:
    enabled: true
    labels:
      - sre-agent
      - automated
      - ci-failure
    assignees: []

# Only monitor specific workflows (empty = all)
workflows: []

# Ignore patterns
ignore:
  conclusions:
    - cancelled  # Don't process cancelled workflows
  branches:
    - "dependabot/*"  # Ignore dependabot branches
